//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeginMobile.LocalizeResources.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeginMobile.LocalizeResources.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string AlertOk {
            get {
                return ResourceManager.GetString("AlertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re - Try.
        /// </summary>
        public static string AlertReTry {
            get {
                return ResourceManager.GetString("AlertReTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Contacts.
        /// </summary>
        public static string AppHomeChildFindContacts {
            get {
                return ResourceManager.GetString("AppHomeChildFindContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string AppHomeChildGroups {
            get {
                return ResourceManager.GetString("AppHomeChildGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string AppHomeChildMessages {
            get {
                return ResourceManager.GetString("AppHomeChildMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Feed.
        /// </summary>
        public static string AppHomeChildNewsFeed {
            get {
                return ResourceManager.GetString("AppHomeChildNewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string AppHomeChildNotifications {
            get {
                return ResourceManager.GetString("AppHomeChildNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string AppHomeTitle {
            get {
                return ResourceManager.GetString("AppHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string ApplicationValidationError {
            get {
                return ResourceManager.GetString("ApplicationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string ButtonAcceptFriend {
            get {
                return ResourceManager.GetString("ButtonAcceptFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        public static string ButtonAddFriend {
            get {
                return ResourceManager.GetString("ButtonAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Friend Request.
        /// </summary>
        public static string ButtonCancelRequestFriend {
            get {
                return ResourceManager.GetString("ButtonCancelRequestFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ButtonChangePasswordSend {
            get {
                return ResourceManager.GetString("ButtonChangePasswordSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ButtonForgotPassword {
            get {
                return ResourceManager.GetString("ButtonForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string ButtonReadNotification {
            get {
                return ResourceManager.GetString("ButtonReadNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string ButtonRejectFriend {
            get {
                return ResourceManager.GetString("ButtonRejectFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ButtonRemoveFriend {
            get {
                return ResourceManager.GetString("ButtonRemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ButtonSend {
            get {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string ButtonSendMessage {
            get {
                return ResourceManager.GetString("ButtonSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        public static string ButtonUnReadNotification {
            get {
                return ResourceManager.GetString("ButtonUnReadNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your Password.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string EditorMessagePlaceholder {
            get {
                return ResourceManager.GetString("EditorMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string EntryConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("EntryConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EntryEmailPlaceholder {
            get {
                return ResourceManager.GetString("EntryEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string EntryFullNamePlaceholder {
            get {
                return ResourceManager.GetString("EntryFullNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string EntryPasswordPlaceholder {
            get {
                return ResourceManager.GetString("EntryPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string EntrySubjectPlaceholder {
            get {
                return ResourceManager.GetString("EntrySubjectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string EntryUsernamePlaceholder {
            get {
                return ResourceManager.GetString("EntryUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To (Username or Friend&apos;s Name).
        /// </summary>
        public static string EntryUsernamePlaceholderMessage {
            get {
                return ResourceManager.GetString("EntryUsernamePlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email address for reset your password.
        /// </summary>
        public static string ForgotPassAlertCheckEmail {
            get {
                return ResourceManager.GetString("ForgotPassAlertCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened on the server.
        /// </summary>
        public static string ForgotPassAlertErrorServer {
            get {
                return ResourceManager.GetString("ForgotPassAlertErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string ForgotPassAlertInformation {
            get {
                return ResourceManager.GetString("ForgotPassAlertInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the e-mail address you registered with the Application. Instructions to reset your password will be sent to this address..
        /// </summary>
        public static string ForgotPassLabelEnterEmail {
            get {
                return ResourceManager.GetString("ForgotPassLabelEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        public static string ForgotPassLabelPasswordRecovery {
            get {
                return ResourceManager.GetString("ForgotPassLabelPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address.
        /// </summary>
        public static string ForgotPassPlaceHolderEmail {
            get {
                return ResourceManager.GetString("ForgotPassPlaceHolderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has wrong format.
        /// </summary>
        public static string ForgotPassValidationEmail {
            get {
                return ResourceManager.GetString("ForgotPassValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        public static string HelpCenterTitle {
            get {
                return ResourceManager.GetString("HelpCenterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My activity.
        /// </summary>
        public static string LabelActivityTitle {
            get {
                return ResourceManager.GetString("LabelActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Received.
        /// </summary>
        public static string LabelDateReceived {
            get {
                return ResourceManager.GetString("LabelDateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string LabelDetailPageHome {
            get {
                return ResourceManager.GetString("LabelDetailPageHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LabelEventDate {
            get {
                return ResourceManager.GetString("LabelEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name.
        /// </summary>
        public static string LabelEventName {
            get {
                return ResourceManager.GetString("LabelEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string LabelEventTitle {
            get {
                return ResourceManager.GetString("LabelEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knocks.
        /// </summary>
        public static string LabelMenuKnocks {
            get {
                return ResourceManager.GetString("LabelMenuKnocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string LabelMenuTitle {
            get {
                return ResourceManager.GetString("LabelMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string LabelNotification {
            get {
                return ResourceManager.GetString("LabelNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string LabelProfileMeTitle {
            get {
                return ResourceManager.GetString("LabelProfileMeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string LabelShopDate {
            get {
                return ResourceManager.GetString("LabelShopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string LabelShopPrice {
            get {
                return ResourceManager.GetString("LabelShopPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string LabelShopTitle {
            get {
                return ResourceManager.GetString("LabelShopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string LabelTitleProfile {
            get {
                return ResourceManager.GetString("LabelTitleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error login validation.
        /// </summary>
        public static string LoginAlertValidationError {
            get {
                return ResourceManager.GetString("LoginAlertValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Password are required.
        /// </summary>
        public static string LoginAlertValidationUsernameAndPass {
            get {
                return ResourceManager.GetString("LoginAlertValidationUsernameAndPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Form.
        /// </summary>
        public static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string OptionAllCategories {
            get {
                return ResourceManager.GetString("OptionAllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Category.
        /// </summary>
        public static string PickerEventFilterBycategory {
            get {
                return ResourceManager.GetString("PickerEventFilterBycategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string PlaceholderChangePasswordConfirmNewPass {
            get {
                return ResourceManager.GetString("PlaceholderChangePasswordConfirmNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string PlaceholderChangePasswordNewPass {
            get {
                return ResourceManager.GetString("PlaceholderChangePasswordNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string PrivacyTitle {
            get {
                return ResourceManager.GetString("PrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required.
        /// </summary>
        public static string RegisterAlertFieldsAreRequired {
            get {
                return ResourceManager.GetString("RegisterAlertFieldsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully registered..
        /// </summary>
        public static string RegisterAlertSuccessMessage {
            get {
                return ResourceManager.GetString("RegisterAlertSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has wrong format.
        /// </summary>
        public static string RegisterAlertValidationEmail {
            get {
                return ResourceManager.GetString("RegisterAlertValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password and Confirm Password do not match!.
        /// </summary>
        public static string RegisterAlertValidationPassAndConfirm {
            get {
                return ResourceManager.GetString("RegisterAlertValidationPassAndConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please agree the Terms and Conditions!.
        /// </summary>
        public static string RegisterAlertValidationTermsAndConditions {
            get {
                return ResourceManager.GetString("RegisterAlertValidationTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree the Terms &amp; Conditions.
        /// </summary>
        public static string RegisterButtonTermsAndConditions {
            get {
                return ResourceManager.GetString("RegisterButtonTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterFormTitle {
            get {
                return ResourceManager.GetString("RegisterFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by event name.
        /// </summary>
        public static string SearchViewEventSearchByName {
            get {
                return ResourceManager.GetString("SearchViewEventSearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened on the server.
        /// </summary>
        public static string ServerErrorMessage {
            get {
                return ResourceManager.GetString("ServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string ServerErrorMessageName {
            get {
                return ResourceManager.GetString("ServerErrorMessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfuly.
        /// </summary>
        public static string ServerMessageChangePassword {
            get {
                return ResourceManager.GetString("ServerMessageChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull!.
        /// </summary>
        public static string ServerMessageSuccess {
            get {
                return ResourceManager.GetString("ServerMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop detail.
        /// </summary>
        public static string ShopItemPageTitle {
            get {
                return ResourceManager.GetString("ShopItemPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string TermsAndConditionsButtonGoBack {
            get {
                return ResourceManager.GetString("TermsAndConditionsButtonGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions.
        /// </summary>
        public static string TermsAndConditionsLabelTermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditionsLabelTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsAndConditionsTitle {
            get {
                return ResourceManager.GetString("TermsAndConditionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ToolBarProfileMeContacts {
            get {
                return ResourceManager.GetString("ToolBarProfileMeContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string ToolBarProfileMeEvents {
            get {
                return ResourceManager.GetString("ToolBarProfileMeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string ToolBarProfileMeGroups {
            get {
                return ResourceManager.GetString("ToolBarProfileMeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string ToolBarProfileMeInfo {
            get {
                return ResourceManager.GetString("ToolBarProfileMeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string ToolBarProfileMeMessages {
            get {
                return ResourceManager.GetString("ToolBarProfileMeMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyActv.
        /// </summary>
        public static string ToolBarProfileMeMyAct {
            get {
                return ResourceManager.GetString("ToolBarProfileMeMyAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string ToolBarProfileMeShop {
            get {
                return ResourceManager.GetString("ToolBarProfileMeShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated successfuly.
        /// </summary>
        public static string UpdateProfileAlertMessage {
            get {
                return ResourceManager.GetString("UpdateProfileAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfuly updated!.
        /// </summary>
        public static string UpdateProfileAlertSuccess {
            get {
                return ResourceManager.GetString("UpdateProfileAlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateProfileButtonUpdate {
            get {
                return ResourceManager.GetString("UpdateProfileButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and Surname.
        /// </summary>
        public static string UpdateProfileEntryNameSurname {
            get {
                return ResourceManager.GetString("UpdateProfileEntryNameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile.
        /// </summary>
        public static string UpdateProfileTitle {
            get {
                return ResourceManager.GetString("UpdateProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
    }
}
