#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BeginMobile.Android.Resource", IsApplication=true)]

namespace BeginMobile.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a_event = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int about_us = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int activity = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BadgeCircle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int badgedefault = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int call_center = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int groups = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ievents = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ifeed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int igroup = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int iphone_message = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int logotype = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logout = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int mail = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int menunav = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int monoandroidsplash = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int netcomputers = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int offline_icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int online_icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int padlock = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int privacy = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ratingoff = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ratingon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int shop = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int terms_conditions = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int userdefault = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int userdefault3 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int userprofile = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int tab_badge = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int tab_icon = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int tab_title = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BarTabLayout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040002
			public const int ActionBarTab = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ActionBarTabBar = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ActionBarTabText = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int BeginMobileTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
